// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package localloginfilter.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the LocalLoginFilter module
	public static boolean afterStartup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("LocalLoginFilter.AfterStartup").withParams(params).execute(context);
	}
	public static boolean eXAMPLE_FilterUser(IContext context, system.proxies.User _exampleUser)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ExampleUser", _exampleUser == null ? null : _exampleUser.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("LocalLoginFilter.EXAMPLE_FilterUser").withParams(params).execute(context);
	}
}
