// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package blockdefaultlogin.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the BlockDefaultLogin module

	/**
	* Set this value to true to block users attempting to access the application using the default login (e.g. login form instead of SSO).
	*/
	public static boolean getBlockDefaultLogin()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("BlockDefaultLogin.BlockDefaultLogin");
	}
}