// This file was generated by Mendix Modeler 7.12.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package blockdefaultlogin.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the BlockDefaultLogin module

	public static boolean getBlockDefaultLogin()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("BlockDefaultLogin.BlockDefaultLogin");
	}
}